version: "3.8"

services:
  frontend:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend/app

  api: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    command: ./docker-entrypoint.sh

  db:
    image: postgres:10.15
    ports:
      - 5431:5432
    volumes:
      - masterjava:/data/db

volumes:
  masterjava:
